--------------------------------------------------------
--  File created - Tuesday-November-27-2012   
--------------------------------------------------------
DROP TABLE "SCOTT"."ADMIN" cascade constraints;
DROP TABLE "SCOTT"."CATEGORY" cascade constraints;
DROP TABLE "SCOTT"."CUSTOMER" cascade constraints;
DROP TABLE "SCOTT"."ORDERDETAILS" cascade constraints;
DROP TABLE "SCOTT"."PRODUCT" cascade constraints;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ADMIN" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"CONTACTNO" NUMBER(20,0), 
	"SHIPPINGCHARGES" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CATEGORY" 
   (	"CNAME" VARCHAR2(50 BYTE), 
	"CDESC" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CUSTOMER" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(32 BYTE), 
	"FIRSTNAME" VARCHAR2(15 BYTE), 
	"LASTNAME" VARCHAR2(15 BYTE), 
	"BILL_ADDRESSLINE1" VARCHAR2(225 BYTE), 
	"BILL_ADDRESSLINE2" VARCHAR2(225 BYTE), 
	"BILL_CITY" VARCHAR2(20 BYTE), 
	"BILL_STATE" VARCHAR2(20 BYTE), 
	"BILL_COUNTRY" VARCHAR2(20 BYTE), 
	"BILL_POSTALCODE" NUMBER, 
	"BILL_CONTACTNO" NUMBER, 
	"SHIP_ADDRESSLINE1" VARCHAR2(225 BYTE), 
	"SHIP_ADDRESSLINE2" VARCHAR2(225 BYTE), 
	"SHIP_CITY" VARCHAR2(20 BYTE), 
	"SHIP_STATE" VARCHAR2(20 BYTE), 
	"SHIP_COUNTRY" VARCHAR2(20 BYTE), 
	"SHIP_POSTALCODE" NUMBER, 
	"SHIP_CONTACTNO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERDETAILS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ORDERDETAILS" 
   (	"OID" NUMBER, 
	"PID" NUMBER, 
	"PQTY" NUMBER, 
	"USERNAME" VARCHAR2(20 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PRODUCT" 
   (	"PID" NUMBER(*,0), 
	"PNAME" VARCHAR2(50 BYTE), 
	"PDESC" VARCHAR2(255 BYTE), 
	"PQTY" NUMBER, 
	"PPRICE" NUMBER, 
	"PAVAILABILITY" VARCHAR2(1 CHAR) DEFAULT 'Y'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.ADMIN
SET DEFINE OFF;
REM INSERTING into SCOTT.CATEGORY
SET DEFINE OFF;
REM INSERTING into SCOTT.CUSTOMER
SET DEFINE OFF;
REM INSERTING into SCOTT.ORDERDETAILS
SET DEFINE OFF;
REM INSERTING into SCOTT.PRODUCT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ORDERDETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ORDERDETAILS_PK" ON "SCOTT"."ORDERDETAILS" ("OID", "PID", "USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CATEGORY_PK" ON "SCOTT"."CATEGORY" ("CNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."ADMIN_PK" ON "SCOTT"."ADMIN" ("USERNAME", "PASSWORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PRODUCT_PK" ON "SCOTT"."PRODUCT" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."CUSTOMER_PK" ON "SCOTT"."CUSTOMER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."CUSTOMER" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."CUSTOMER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."CATEGORY" MODIFY ("CNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDERDETAILS" ADD CONSTRAINT "ORDERDETAILS_PK" PRIMARY KEY ("OID", "PID", "USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."ORDERDETAILS" MODIFY ("OID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDERDETAILS" MODIFY ("PID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ORDERDETAILS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PRODUCT" ADD CONSTRAINT "PRODUCT_CHK1" CHECK (PAVAILABILITY IN ('Y', 'N')) ENABLE;
 
  ALTER TABLE "SCOTT"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."PRODUCT" MODIFY ("PID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."PRODUCT" MODIFY ("PAVAILABILITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("USERNAME", "PASSWORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SCOTT"."ADMIN" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ORDERDETAILS" ADD CONSTRAINT "ORDERDETAILS_PRODUCT_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "SCOTT"."CUSTOMER" ("USERNAME") ON DELETE CASCADE ENABLE;
